[package]
name = "lexi-server"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.43.0", features = ["full"] }
anyhow = "1.0.96"
dotenv = "0.15.0"
url = "2.5.4"

tracing = "0.1.41"
tracing-subscriber = "0.3.19"
